#define FIX_LED_PIN     15
#define ERR_LED_PIN     16
#define BUZZER_SWITCH   29
#define GPS_SWITCH      28
#define GPS_RX_PIN      5
#define GPS_TX_PIN      6
#define KEY1            25
#define KEY2            0
#define KEY3            4
#define KEY4            3
#define GPRS_SWITCH     11
#define GPRS_RX_PIN     9
#define GPRS_TX_PIN     7
#define USD_CS          14
#define USD_MISO        12
#define USD_SCLK        10
#define USD_MOSI        8
#define USD_CARD        19
#define LCD_RST         30
#define LCD_CS          22
#define LCD_DC          21 
#define LCD_MOSI        23
#define LCD_SCLK        24 
#define LCD_BKL         13
#define USB_V_ADC       1
#define BATT_V_ADC      2
